In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv("/home/nhi/WFH_ECU_Project(25Mar20)/Data/big_data(23April20)/project(23April20)/data_shuffle(b_m).csv")

In [3]:
df

labels  B_min  B_max      B_mean       B_std    B_skew  B_kurtosis  \
0          0    118    255  203.558132   62.681773 -0.403019   -1.837075   
1          1      0    255  145.020474  126.004662 -0.277543   -1.922811   
2          1      0    255  136.873236  126.928384 -0.147385   -1.978152   
3          0    120    255  220.989074   56.431372 -1.065332   -0.864294   
4          1      0    255  135.415087  126.998911 -0.124097   -1.984459   
...      ...    ...    ...         ...         ...       ...         ...   
4677       1      0    255  132.992858  126.755855 -0.086434   -1.992240   
4678       0    119    255  200.149819   63.100869 -0.297873   -1.909774   
4679       0    120    255  212.638378   60.144473 -0.722133   -1.477708   
4680       0    120    255  205.599565   61.930899 -0.482881   -1.764840   
4681       1      0    255  168.221138  120.738057 -0.674136   -1.545481   

      B_mode  B_entropy     B_energy  ...     R_energy  h_mean      v_mean  \
0        255  10.799481   148.548274  ...   148.548274       0  203.558132   
1        255  10.291147  1327.389790  ...  1327.389790       0  145.020474   
2        255  10.232555  1196.212191  ...  1196.212191       0  136.873236   
3        255  10.813326   180.070087  ...   180.070087       0  220.989074   
4        255  10.222746  1172.807492  ...  1172.807492       0  135.415087   
...      ...        ...          ...  ...          ...     ...         ...   
4677     255  10.212401  4823.704225  ...  4823.704225       0  132.992858   
4678     255  10.797601   726.003236  ...   726.003236       0  200.149819   
4679     255  10.806131   230.476222  ...   230.476222       0  212.638378   
4680     255  10.801294  1198.161099  ...  1198.161099       0  205.599565   
4681     255  10.435269   332.543839  ...   332.543839       0  168.221138   

      cb_mean  cr_mean   gray_mean      contrast  correlation    energy  \
0         128      128  203.558132    371.989708     0.952714  0.612753   
1         128      128  145.020474   3408.680675     0.892718  0.517615   
2         128      128  136.873236   2952.397860     0.908347  0.548479   
3         128      128  220.989074    385.886749     0.939135  0.671990   
4         128      128  135.415087   2985.061011     0.907426  0.530004   
...       ...      ...         ...           ...          ...       ...   
4677      128      128  132.992858  12981.662196     0.595851  0.280444   
4678      128      128  200.149819   1825.517212     0.770405  0.370028   
4679      128      128  212.638378    597.377412     0.917062  0.621152   
4680      128      128  205.599565   3161.718198     0.586811  0.262579   
4681      128      128  168.221138    898.791977     0.969237  0.685664   

       homogeneity  
0       371.989708  
1      3408.680675  
2      2952.397860  
3       385.886749  
4      2985.061011  
...            ...  
4677  12981.662196  
4678   1825.517212  
4679    597.377412  
4680   3161.718198  
4681    898.791977  

[4682 rows x 37 columns]

In [4]:
def dataSetAnalysis(df):
     #view starting values of data set
    print("Dataset Head")
    print(df.head(3))
    print("=" * 30)
    
     # View How many samples and how many missing values for each feature
    print("Dataset Features Details")
    print(df.info())
    print("=" * 30)
    
    # view distribution of numerical features across the data set
    print("Dataset Numerical Features")
    print(df.describe())
    print("=" * 30)
    
    # view distribution of categorical features across the data set
    #print("Dataset Categorical Features")
    #print(df.describe(include=['O']))
   # print("=" * 30)
    
#dataSetAnalysis(df)

In [4]:
#create a dataframe with all training data except the target column
X = df.iloc[:,1:]

In [1]:
#X

In [11]:
import keras
from keras.utils import to_categorical
# One-hot encode target colunm
y = to_categorical(df.labels)
print(y)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]


In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [6]:
#create model
model_2 = Sequential()

In [7]:
#get number of columns in training data
n_cols_2 = X.shape[1]

In [8]:
#add layers to model
model_2.add(Dense(250, activation='relu', input_shape=(n_cols_2,)))
model_2.add(Dense(250, activation='relu'))
model_2.add(Dense(250, activation='relu'))
model_2.add(Dense(2, activation='softmax'))

In [9]:
model_2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [12]:
from keras.callbacks import EarlyStopping
early_stopping_monitor = EarlyStopping(patience=3)
model_2.fit(X, y, epochs=20, validation_split=0.2, callbacks=[early_stopping_monitor])

Train on 3745 samples, validate on 937 samples
Epoch 1/20
3745/3745 [==============================] - 1s 207us/sample - loss: 10.5487 - accuracy: 0.8846 - val_loss: 0.0522 - val_accuracy: 0.9872
Epoch 2/20
3745/3745 [==============================] - 0s 97us/sample - loss: 0.0632 - accuracy: 0.9923 - val_loss: 0.0025 - val_accuracy: 0.9979
Epoch 3/20
3745/3745 [==============================] - 0s 100us/sample - loss: 0.0666 - accuracy: 0.9912 - val_loss: 0.1671 - val_accuracy: 0.9733
Epoch 4/20
3745/3745 [==============================] - 0s 99us/sample - loss: 0.3998 - accuracy: 0.9805 - val_loss: 0.0644 - val_accuracy: 0.9915
Epoch 5/20
3745/3745 [==============================] - 0s 98us/sample - loss: 0.4567 - accuracy: 0.9808 - val_loss: 0.0231 - val_accuracy: 0.9968


In [14]:
# Second approach
X = df.iloc[:,1:] # [all rows, col from index 2 to the last one excluding 'Unnamed: 32']
y = df.labels # [all rows, col one only which contains the classes of cancer]

In [15]:
X

B_min  B_max      B_mean       B_std    B_skew  B_kurtosis  B_mode  \
0       118    255  203.558132   62.681773 -0.403019   -1.837075     255   
1         0    255  145.020474  126.004662 -0.277543   -1.922811     255   
2         0    255  136.873236  126.928384 -0.147385   -1.978152     255   
3       120    255  220.989074   56.431372 -1.065332   -0.864294     255   
4         0    255  135.415087  126.998911 -0.124097   -1.984459     255   
...     ...    ...         ...         ...       ...         ...     ...   
4677      0    255  132.992858  126.755855 -0.086434   -1.992240     255   
4678    119    255  200.149819   63.100869 -0.297873   -1.909774     255   
4679    120    255  212.638378   60.144473 -0.722133   -1.477708     255   
4680    120    255  205.599565   61.930899 -0.482881   -1.764840     255   
4681      0    255  168.221138  120.738057 -0.674136   -1.545481     255   

      B_entropy     B_energy  G_min  ...     R_energy  h_mean      v_mean  \
0     10.799481   148.548274    118  ...   148.548274       0  203.558132   
1     10.291147  1327.389790      0  ...  1327.389790       0  145.020474   
2     10.232555  1196.212191      0  ...  1196.212191       0  136.873236   
3     10.813326   180.070087    120  ...   180.070087       0  220.989074   
4     10.222746  1172.807492      0  ...  1172.807492       0  135.415087   
...         ...          ...    ...  ...          ...     ...         ...   
4677  10.212401  4823.704225      0  ...  4823.704225       0  132.992858   
4678  10.797601   726.003236    119  ...   726.003236       0  200.149819   
4679  10.806131   230.476222    120  ...   230.476222       0  212.638378   
4680  10.801294  1198.161099    120  ...  1198.161099       0  205.599565   
4681  10.435269   332.543839      0  ...   332.543839       0  168.221138   

      cb_mean  cr_mean   gray_mean      contrast  correlation    energy  \
0         128      128  203.558132    371.989708     0.952714  0.612753   
1         128      128  145.020474   3408.680675     0.892718  0.517615   
2         128      128  136.873236   2952.397860     0.908347  0.548479   
3         128      128  220.989074    385.886749     0.939135  0.671990   
4         128      128  135.415087   2985.061011     0.907426  0.530004   
...       ...      ...         ...           ...          ...       ...   
4677      128      128  132.992858  12981.662196     0.595851  0.280444   
4678      128      128  200.149819   1825.517212     0.770405  0.370028   
4679      128      128  212.638378    597.377412     0.917062  0.621152   
4680      128      128  205.599565   3161.718198     0.586811  0.262579   
4681      128      128  168.221138    898.791977     0.969237  0.685664   

       homogeneity  
0       371.989708  
1      3408.680675  
2      2952.397860  
3       385.886749  
4      2985.061011  
...            ...  
4677  12981.662196  
4678   1825.517212  
4679    597.377412  
4680   3161.718198  
4681    898.791977  

[4682 rows x 36 columns]

In [16]:
y

0       0
1       1
2       1
3       0
4       1
       ..
4677    1
4678    0
4679    0
4680    0
4681    1
Name: labels, Length: 4682, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [18]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

In [20]:
def build_classifier(optimizer):

    classifier = Sequential()
    classifier.add(Dense(units = 16, kernel_initializer = 'uniform', activation = 'relu', input_dim = 30))
    classifier.add(Dense(units = 8, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])

    return classifier

In [21]:
classifier = KerasClassifier(build_fn = build_classifier)
#The batch size is a number of samples processed before the model is updated.
#The number of epochs is the number of complete passes through the training dataset.
parameters = {'batch_size': [1, 5],
               'epochs': [100, 120],
               'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier,
                            param_grid = parameters,
                            scoring = 'accuracy',
                            cv = 10)

In [22]:
grid_search = grid_search.fit(X_train, y_train)

/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_1_input to have shape (30,) but got array with shape (36,)

  FitFailedWarning)
/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_5_input to have shape (30,) but got array with shape (36,)

  FitFailedWarning)
/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_9_input to have shape (30,)

/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_97_input to have shape (30,) but got array with shape (36,)

  FitFailedWarning)
/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_101_input to have shape (30,) but got array with shape (36,)

  FitFailedWarning)
/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_105_input to have shape 

/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_197_input to have shape (30,) but got array with shape (36,)

  FitFailedWarning)
/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_201_input to have shape (30,) but got array with shape (36,)

  FitFailedWarning)
/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_205_input to have shape

/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_305_input to have shape (30,) but got array with shape (36,)

  FitFailedWarning)
/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_309_input to have shape (30,) but got array with shape (36,)

  FitFailedWarning)
/home/nhi/venv/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Error when checking input: expected dense_313_input to have shape

ValueError: Error when checking input: expected dense_321_input to have shape (30,) but got array with shape (36,)

In [29]:
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_
print("best_parameters: ")
print(best_parameters)
print("\nbest_accuracy: ")
print(best_accuracy)

best_parameters: 
{'batch_size': 1, 'epochs': 10, 'optimizer': 'adam'}

best_accuracy: 
nan


In [32]:
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential() # Initialising the ANN

In [33]:
classifier.add(Dense(units = 16, kernel_initializer = 'uniform', activation = 'relu', input_dim = 30))
classifier.add(Dense(units = 8, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [34]:
classifier.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [40]:
classifier.fit(X_train, y_train, batch_size = 1, epochs = 100)

Epoch 1/100
3745/3745 [==============================] - 5s 1ms/step - loss: -25293742388.8953 - accuracy: 0.4641
Epoch 2/100
3745/3745 [==============================] - 5s 1ms/step - loss: -36273520137.7021 - accuracy: 0.4636
Epoch 3/100
3745/3745 [==============================] - 5s 1ms/step - loss: -50626894031.6649 - accuracy: 0.4633
Epoch 4/100
3745/3745 [==============================] - 5s 1ms/step - loss: -68856194846.9892 - accuracy: 0.4646
Epoch 5/100
3745/3745 [==============================] - 5s 1ms/step - loss: -91542731058.9649 - accuracy: 0.4628
Epoch 6/100
3745/3745 [==============================] - 5s 1ms/step - loss: -119407035778.6867 - accuracy: 0.4630
Epoch 7/100
3745/3745 [==============================] - 5s 1ms/step - loss: -153249505434.5389 - accuracy: 0.4617
Epoch 8/100
3745/3745 [==============================] - 5s 1ms/step - loss: -193868844683.2828 - accuracy: 0.4638
Epoch 9/100
3745/3745 [==============================] - 5s 1ms/step - loss: -2421073

In [41]:
from keras.models import load_model

In [42]:
y_pred = classifier.predict(X_test)
y_pred = [ 1 if y>=0.5 else 0 for y in y_pred ]

In [43]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[450  39   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0]
 [  0  36   0   0   0   0   0   0]
 [  0 191   0   0   0   0   0   0]
 [  0 198   0   0   0   0   0   0]
 [  0  21   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0]]


In [45]:
accuracy = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1])
print("Accuracy: "+ str(accuracy*100)+"%")

Accuracy: 92.02453987730061%
