In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("/home/nhi/WFH_ECU_Project(25Mar20)/Data/big_data(23Mar20)/project(23Mar20)/data_shuffle(b_m).csv")

In [6]:
df

ID  B_min  B_max      B_mean       B_std    B_skew  B_kurtosis  B_mode  \
0      0    118    255  203.558132   62.681773 -0.403019   -1.837075     255   
1      1      0    255  145.020474  126.004662 -0.277543   -1.922811     255   
2      1      0    255  136.873236  126.928384 -0.147385   -1.978152     255   
3      0    120    255  220.989074   56.431372 -1.065332   -0.864294     255   
4      1      0    255  135.415087  126.998911 -0.124097   -1.984459     255   
...   ..    ...    ...         ...         ...       ...         ...     ...   
4677   1      0    255  132.992858  126.755855 -0.086434   -1.992240     255   
4678   0    119    255  200.149819   63.100869 -0.297873   -1.909774     255   
4679   0    120    255  212.638378   60.144473 -0.722133   -1.477708     255   
4680   0    120    255  205.599565   61.930899 -0.482881   -1.764840     255   
4681   1      0    255  168.221138  120.738057 -0.674136   -1.545481     255   

      B_entropy     B_energy  ...     R_energy  h_mean      v_mean  cb_mean  \
0     10.799481   148.548274  ...   148.548274       0  203.558132      128   
1     10.291147  1327.389790  ...  1327.389790       0  145.020474      128   
2     10.232555  1196.212191  ...  1196.212191       0  136.873236      128   
3     10.813326   180.070087  ...   180.070087       0  220.989074      128   
4     10.222746  1172.807492  ...  1172.807492       0  135.415087      128   
...         ...          ...  ...          ...     ...         ...      ...   
4677  10.212401  4823.704225  ...  4823.704225       0  132.992858      128   
4678  10.797601   726.003236  ...   726.003236       0  200.149819      128   
4679  10.806131   230.476222  ...   230.476222       0  212.638378      128   
4680  10.801294  1198.161099  ...  1198.161099       0  205.599565      128   
4681  10.435269   332.543839  ...   332.543839       0  168.221138      128   

      cr_mean   gray_mean      contrast  correlation    energy   homogeneity  
0         128  203.558132    371.989708     0.952714  0.612753    371.989708  
1         128  145.020474   3408.680675     0.892718  0.517615   3408.680675  
2         128  136.873236   2952.397860     0.908347  0.548479   2952.397860  
3         128  220.989074    385.886749     0.939135  0.671990    385.886749  
4         128  135.415087   2985.061011     0.907426  0.530004   2985.061011  
...       ...         ...           ...          ...       ...           ...  
4677      128  132.992858  12981.662196     0.595851  0.280444  12981.662196  
4678      128  200.149819   1825.517212     0.770405  0.370028   1825.517212  
4679      128  212.638378    597.377412     0.917062  0.621152    597.377412  
4680      128  205.599565   3161.718198     0.586811  0.262579   3161.718198  
4681      128  168.221138    898.791977     0.969237  0.685664    898.791977  

[4682 rows x 37 columns]

In [7]:
X = np.array(df.iloc[:,1:])
y = np.array(df.ID)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print("X_train: ", X_train.shape)
print("X_test: ", X_test.shape)
print("y_train: ", y_train.shape)
print("y_test: ", y_test.shape)

X_train:  (3511, 36)
X_test:  (1171, 36)
y_train:  (3511,)
y_test:  (1171,)


In [9]:
# Data standardisation
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
# Decision Tree Classification
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy',random_state = 0)
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)
#print(y_pred)

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix: \n{}".format(cm))

from sklearn.metrics import accuracy_score
print("accuracy score:{}".format(accuracy_score(y_test, y_pred))) 

confusion matrix: 
[[587   0]
 [  1 583]]
accuracy score:0.9991460290350128


In [16]:
#NB Gaussian
from sklearn .naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train)
y_pred = nb.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix: \n{}".format(cm))

from sklearn.metrics import accuracy_score
print("accuracy score:{}".format(accuracy_score(y_test, y_pred)))

confusion matrix: 
[[586   1]
 [  0 584]]
accuracy score:0.9991460290350128


In [19]:
# Random Forest Classification
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy',random_state = 0)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix: \n{}".format(cm))

from sklearn.metrics import accuracy_score
print("accuracy score:{}".format(accuracy_score(y_test, y_pred)))

confusion matrix: 
[[587   0]
 [  1 583]]
accuracy score:0.9991460290350128
